title: Lettro
email: hi@koddr.io
description: >- # this means to ignore newlines until "baseurl:"
  Lettro is an email marketing powerhouse in your Terminal.

# Build settings
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
